import type { Metadata } from "next";
import localFont from "next/font/local";
import "./page.module.css";
// import { Kumbh_Sans, Nunito, Outfit,Lora } from 'next/font/google'
import "/public/assets/css/plugins/bootstrap.min.css"
import "/public/assets/css/plugins/font-awesome-pro.css"
import "/public/assets/css/plugins/nice-select.css"
import "/public/assets/css/plugins/swiper.bundle.css"
import "/public/assets/icon/font-awesome/css/all.css"
// import "/public/assets/css/plugins/owl.carousel.min.css"
import "/public/assets/css/plugins/modal-video.min.css"
import "/public/assets/css/plugins/mobile.css"
import "/public/assets/css/plugins/aos.css"
import "/public/assets/css/typography.css"
import "/public/assets/css/master.css"
import "/public/assets/css/plugins/responsive.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
